### ISSUE TITLE
add_index does not seem to work

### ISSUE THREAD

**Issue by jogaco** [steverice/pt-osc#7]
It does nothing.
Am I missing anything?
Tried both within plain Migration class and PtOscMigration class.
I have ended up using an execute command within a PtOscMigration class.

**Comment by steverice** [comment]
@jogaco Can you provide your `database.yml` config as well as the command in your migration?

**Comment by jogaco** [comment]
database.yml

```
dev_percona:
  adapter: mysql_pt_osc
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  database: my_project_dev
  pool: 5
  username: root
  host: 127.0.0.1
  port: 3306
  percona:
    defaults-file: /etc/mysql/percona-user.cnf
    execute: true
    log: ./log/pt-schema.log
```

Command:

```
env RAILS_ENV=dev_percona rake db:migrate
```
